#!/bin/bash
set -e
if [ "$#" -ne 2 ];then
    echo "usage:"
    echo "$0 <windowname> <outputdir>"
    exit 1
fi

OUTDIR=$2

FOO=`xwininfo -name $1`
SIZE=`echo $FOO | perl -n -e'/-geometry\s+(\d+)x(\d+)[+](\d+)[+](\d+)/ && print $1."x".$2'`
OFFSET=`echo $FOO | perl -n -e'/-geometry\s+(\d+)x(\d+)[+](\d+)[+](\d+)/ && print $3.",".$4'`


mkdir -p $OUTDIR

echo -n "in "
for i in 3 2 1
do
    echo -n $i...
    sleep 1
done
echo "go!"



# ffmpeg -f x11grab -r 50 -s $SIZE -i :0.0+$OFFSET -vcodec gif $OUTDIR/out%04d.gif
ffmpeg -f x11grab -r 50 -s $SIZE -i :0.0+$OFFSET -vcodec png $OUTDIR/out%04d.png



# best blog about imagemagick gif creation:
# https://room208.org/blog/posts/48793543478.html

# $ cd capdir
# $ convert -resize 50% -fuzz 5% -delay 1x50 -coalesce -layers OptimizeTransparency $(seq -f out%04g.png 1 225) dude_gallery.gif


# or 
# $ gifsicle --delay 2 --loop *.png >animation.gif
# $ convert -layers Optimize animation.gif animation_optimized.gif


