.TH ZIG 6 "06 September 2020"
.SH NAME
zig \- it's a game where you shoot stuff
.SH SYNOPSIS
.B zig
.RI [ -fullscreen | -window ] [-nosound]
.SH DESCRIPTION
.B ZIG
is a fast action, retro-style, single-player arcade game.
The player progresses through each of the 50 levels by dealing flaming electric laser death to the assortment of opponents in each level.

The player is controlled using either gamepad or keyboard.

.SH OPTIONS
.TP
\fB\-fullscreen\fR
run in fullscreen mode (default).
.TP
\fB\-window\fR
run in windowed mode.
.TP
\fB\-nosound\fR
run without sound.

.SH KEYS
.TP
.B Left, Right, Up, Down (or W,A,S,D)
Rotate and thrust forward/backwards.
.TP
.B Ctrl, Shift or Space
Fire.
.TP
.B Esc
Pause the game.
.BR
.SH AUTHOR
Zig was written by Ben Campbell <ben@scumways.com>.

