#!/bin/bash
# cheesy little platform-detection script to simplify makefile

if [[ -n "$EMSCRIPTEN" ]]; then
    echo emscripten
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo osx
elif [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
    echo win32
else
    exit 1
fi

